<?php

namespace Database\Seeders;

use App\Models\constituentEntity;
use Illuminate\Database\Seeder;

class ConstituentEntitySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @param constituentEntity $entity
     * @return void
     */
    public function run(ConstituentEntity $entity)
    {
        $levels = [
            ['fias_code' => 01,
                'title' => 'Республика Адыгея (Адыгея)'],
            ['fias_code' => 02,
                'title' => 'Республика Башкортостан'],
            ['fias_code' => 03,
                'title' => 'Республика Бурятия'],
            ['fias_code' => 04,
                'title' => 'Республика Алтай'],
            ['fias_code' => 05,
                'title' => 'Республика Дагестан'],
            ['fias_code' => 06,
                'title' => 'Республика Ингушетия'],
            ['fias_code' => 07,
                'title' => 'Кабардино-Балкарская Республика'],
            ['fias_code' => 8,
                'title' => 'Республика Калмыкия'],
            ['fias_code' => 9,
                'title' => 'Карачаево-Черкесская Республика'],
            ['fias_code' => 10,
                'title' => 'Республика Карелия'],
            ['fias_code' => 11,
                'title' => 'Республика Коми'],
            ['fias_code' => 12,
                'title' => 'Республика Марий Эл'],
            ['fias_code' => 13,
                'title' => 'Республика Мордовия'],
            ['fias_code' => 14,
                'title' => 'Республика Саха (Якутия)'],
            ['fias_code' => 15,
                'title' => 'Республика Северная Осетия - Алания'],
            ['fias_code' => 16,
                'title' => 'Республика Татарстан (Татарстан)'],
            ['fias_code' => 17,
                'title' => 'Республика Тыва'],
            ['fias_code' => 18,
                'title' => 'Удмуртская Республика'],
            ['fias_code' => 19,
                'title' => 'Республика Хакасия'],
            ['fias_code' => 20,
                'title' => 'Чеченская Республика'],
            ['fias_code' => 21,
                'title' => 'Чувашская Республика - Чувашия'],
            ['fias_code' => 22,
                'title' => 'Алтайский край'],
            ['fias_code' => 23,
                'title' => 'Краснодарский край'],
            ['fias_code' => 24,
                'title' => 'Красноярский край'],
            ['fias_code' => 25,
                'title' => 'Приморский край'],
            ['fias_code' => 26,
                'title' => 'Ставропольский край'],
            ['fias_code' => 27,
                'title' => 'Хабаровский край'],
            ['fias_code' => 28,
                'title' => 'Амурская область'],
            ['fias_code' => 29,
                'title' => 'Архангельская область'],
            ['fias_code' => 30,
                'title' => 'Астраханская область'],
            ['fias_code' => 31,
                'title' => 'Белгородская область'],
            ['fias_code' => 32,
                'title' => 'Брянская область'],
            ['fias_code' => 33,
                'title' => 'Владимирская область'],
            ['fias_code' => 34,
                'title' => 'Волгоградская область'],
            ['fias_code' => 35,
                'title' => 'Вологодская область'],
            ['fias_code' => 36,
                'title' => 'Воронежская область'],
            ['fias_code' => 37,
                'title' => 'Ивановская область'],
            ['fias_code' => 38,
                'title' => 'Иркутская область'],
            ['fias_code' => 39,
                'title' => 'Калининградская область'],
            ['fias_code' => 40,
                'title' => 'Калужская область'],
            ['fias_code' => 41,
                'title' => 'Камчатский край'],
            ['fias_code' => 42,
                'title' => 'Кемеровская область'],
            ['fias_code' => 43,
                'title' => 'Кировская область'],
            ['fias_code' => 44,
                'title' => 'Костромская область'],
            ['fias_code' => 45,
                'title' => 'Курганская область'],
            ['fias_code' => 46,
                'title' => 'Курская область'],
            ['fias_code' => 47,
                'title' => 'Ленинградская область'],
            ['fias_code' => 48,
                'title' => 'Липецкая область'],
            ['fias_code' => 49,
                'title' => 'Магаданская область'],
            ['fias_code' => 50,
                'title' => 'Московская область'],
            ['fias_code' => 51,
                'title' => 'Мурманская область'],
            ['fias_code' => 52,
                'title' => 'Нижегородская область'],
            ['fias_code' => 53,
                'title' => 'Новгородская область'],
            ['fias_code' => 54,
                'title' => 'Новосибирская область'],
            ['fias_code' => 55,
                'title' => 'Омская область'],
            ['fias_code' => 56,
                'title' => 'Оренбургская область'],
            ['fias_code' => 57,
                'title' => 'Орловская область'],
            ['fias_code' => 58,
                'title' => 'Пензенская область'],
            ['fias_code' => 59,
                'title' => 'Пермский край'],
            ['fias_code' => 60,
                'title' => 'Псковская область'],
            ['fias_code' => 61,
                'title' => 'Ростовская область'],
            ['fias_code' => 62,
                'title' => 'Рязанская область'],
            ['fias_code' => 63,
                'title' => 'Самарская область'],
            ['fias_code' => 64,
                'title' => 'Саратовская область'],
            ['fias_code' => 65,
                'title' => 'Сахалинская область'],
            ['fias_code' => 66,
                'title' => 'Свердловская область'],
            ['fias_code' => 67,
                'title' => 'Смоленская область'],
            ['fias_code' => 68,
                'title' => 'Тамбовская область'],
            ['fias_code' => 69,
                'title' => 'Тверская область'],
            ['fias_code' => 70,
                'title' => 'Томская область'],
            ['fias_code' => 71,
                'title' => 'Тульская область'],
            ['fias_code' => 72,
                'title' => 'Тюменская область'],
            ['fias_code' => 73,
                'title' => 'Ульяновская область'],
            ['fias_code' => 74,
                'title' => 'Челябинская область'],
            ['fias_code' => 75,
                'title' => 'Забайкальский край'],
            ['fias_code' => 76,
                'title' => 'Ярославская область'],
            ['fias_code' => 77,
                'title' => 'Г. Москва'],
            ['fias_code' => 78,
                'title' => 'Г. Санкт-Петербург'],
            ['fias_code' => 79,
                'title' => 'Еврейская автономная область'],
            ['fias_code' => 83,
                'title' => 'Ненецкий автономный округ'],
            ['fias_code' => 86,
                'title' => 'Ханты-Мансийский автономный округ - Югра'],
            ['fias_code' => 87,
                'title' => 'Чукотский автономный округ'],
            ['fias_code' => 89,
                'title' => 'Ямало-Ненецкий автономный округ'],
            ['fias_code' => 91,
                'title' => 'Республика Крым'],
            ['fias_code' => 92,
                'title' => 'Г. Севастополь'],
            ['fias_code' => 99,
                'title' => 'Иные территории, включая город и космодром Байконур'],
        ];
        $entity::insert($levels);
    }
}
